package com.oyoke.iara.quote

object QuoteRepository {
    fun random(): QuoteModel {
        val position = (quotes.indices).random()
        val selectedQuote = quotes[position]
        return selectedQuote
    }
    private val quotes = listOf(
        QuoteModel("Tu amor es el latido más grande de mi vida."),
        QuoteModel("Sin ser lo que buscaba, terminaste siendo lo que necesito."),
        QuoteModel("Te mereces que te besen, cada día, cada hora, a cada minuto."),
        QuoteModel("Al amor y a ti os conocí el mismo día."),
        QuoteModel("Lo primero que hago al despertar es pensar en ti."),
        QuoteModel("Le doy a todos mi sonrisa, pero sólo a una mi corazón."),
        QuoteModel("Ninguna medida de tiempo contigo será suficiente, pero empecemos con un para siempre."),
        QuoteModel("Si no te hubiera conocido, te habría soñado."),
        QuoteModel("Cada mañana cuando despierto, tú eres la razón por la que sonrío."),
        QuoteModel("Te quiero para volvernos locos de risa, ebrios de nada y pasear sin prisa por las calles, eso sí, tomados de la mano, mejor dicho, del corazón."),
        QuoteModel("Me gusta cuando somos."),
        QuoteModel("Vamos a crear la historia de amor más bonita del mundo."),
        QuoteModel("Temo tanto a la muerte como a la posibilidad de no verte más."),
        QuoteModel("No sé hacia dónde vamos, lo que sé es que quiero ir contigo."),
        QuoteModel("Fuiste, eres y siempre serás mi más bonita casualidad."),
        QuoteModel("Tengo ganas de un futuro contigo."),
        QuoteModel("Un pedacito de tus labios es un pedacito del cielo."),
        QuoteModel("Te miraré cada día como se mira el mar por primera vez."),
        QuoteModel("Que la casualidad nos dure para siempre."),
        QuoteModel("Cuando me sonríes, me haces volar. Y cuando te pienso el sol alumbra más."),
        QuoteModel("Anoche soñé contigo y esta mañana no quería despertar."),
        QuoteModel("Que me perdone el tiempo… por querer detenerlo cuando te miro."),
        QuoteModel("Si tuviera que volver a comenzar mi vida, intentaría encontrarte mucho antes."),
        QuoteModel("Si quieres saber cuánto te amo, solo cuenta las estrellas."),
        QuoteModel("Eres mi todo, mi más, mi siempre."),
        QuoteModel("Que la suerte de conocerte me dure siempre."),
        QuoteModel("Qué cosa más bonita es verte, mientras me ves, viéndote a ti."),
        QuoteModel("No es que tuviera mala suerte en el amor, la vida me estaba haciendo esperarte."),
        QuoteModel("Te amo más de lo que piensas, más de lo que digo y sobre todo más de lo que te demuestro."),
        QuoteModel("No hay día que no te piense, ni noche que no te extrañe."),
        QuoteModel("Eres tú la historia más bonita de mi vida."),
        QuoteModel("Tus ojos están como para perderse en ellos."),
        QuoteModel("Voy a robarle todos los minutos posibles al tiempo, para así estar contigo para siempre."),
        QuoteModel("Mi vida, de todas las definiciones que existen para el amor, tú eres mi favorita."),
        QuoteModel("Tú déjate conquistar, yo me encargo de hacerte feliz."),
        QuoteModel("Amor era solo una palabra, hasta que llegaste para darle sentido."),
        QuoteModel("Sin buscarte te encontré, entre todas las personas del mundo."),
        QuoteModel("Eres la forma más bonita que ha tenido la vida de enseñarme que vale la pena arriesgarse a amar."),
        QuoteModel("Yo no sé tú, pero yo te quiero presente en mi vida."),
        QuoteModel("Mi corazón es perfecto porque tú estás dentro de él."),
        QuoteModel("Me da igual dónde, lo único que quiero es que sea junto a ti."),
        QuoteModel("Ahora sé que tú eras el destino al que yo quería llegar."),
        QuoteModel("Ya era hora de que me tocara alguien como tú."),
        QuoteModel("No sabía lo que quería hasta que quería verte todos los días."),
        QuoteModel("Te amo para amarte y no para ser amado, puesto que nada me place tanto como verte a ti feliz."),
        QuoteModel("Estrellarme en tu boca sería un grave accidente, pero asumo con todo placer las consecuencias."),
        QuoteModel("Pensando en mi felicidad, me acordé de ti."),
        QuoteModel("Te quise en el pasado, te quiero en el presente y si me lo permites, te querré eternamente."),
        QuoteModel("Crear contigo el amor y hacer contigo la vida."),
        QuoteModel("Quiero que seas mi estrella para que me acompañes en mis noches de soledad."),
        QuoteModel("Contigo todo."),
        QuoteModel("Te amo."),
        QuoteModel("Te quiero."),
        QuoteModel("Te adoro."),
        QuoteModel("Me encantas."),
        QuoteModel("Ayer eras mi capricho. Hoy eres mi amor. Mañana serás mi vida."),
        QuoteModel("Nos conocimos una tarde, y ahora no podría olvidarte ni en un millón de años."),
        QuoteModel("Creo que nací para encontrarme contigo."),
        QuoteModel("Si con un beso pudiera demostrar mi amor te estaría besando siempre."),
        QuoteModel("Tú eres la historia más bonita que el destino escribió en mi vida."),
        QuoteModel("Estar sin ti es como vivir en una eterna noche sin estrellas."),
        QuoteModel("Mi amor por ti es mucho más que amor, es algo que se amasa día a día, es proyectar tu sombra junto a mí, hacer con ellas una sola vida."),
        QuoteModel("Eres la luz que ilumina mis días."),
        QuoteModel("No solo me encantas, sino que me complementas."),
        QuoteModel("Cuanto más te conozco, más me quiero contigo."),
        QuoteModel("Eres la historia que siempre me gusta contar."),
        QuoteModel("Haces que mi alma se despierte con tu luz."),
        QuoteModel("Nuestro encuentro no fue una coincidencia. Nada ocurre por accidente."),
        QuoteModel("Vuélveme tu suspiro y subiré y bajaré de tu pecho."),
        QuoteModel("No importa lo que pase mañana o el resto de mi vida. Ahora soy feliz porque te quiero."),
        QuoteModel("Qué bonito es tenerte cerca."),
        QuoteModel("Contigo me iría al fin del mundo."),
        QuoteModel("Si no existieras, yo te inventaría."),
        QuoteModel("La vida es más divertida contigo a mi lado."),
        QuoteModel("No te quería en mi vida, pero al final te cogí cariño."),
        QuoteModel("Después de todo no estamos tan lejos… tú y yo vemos la misma luna, ¿cierto?"),
        QuoteModel("Espero que te veas a ti misma como yo te veo: asombrosa, increíble, amable, inteligente, compasiva, divertida y maravillosa."),
        QuoteModel("La vida sería un poco más aburrida sin ti."),
        QuoteModel("No cabe duda de que soy afortunado, pues he encontrado a la mejor amiga que pude haber imaginado."),
        QuoteModel("Haces mi mundo más bonito, aunque no lo sepas."),
        QuoteModel("Puedes estar lejos de mis ojos, pero no de mis pensamientos."),
        QuoteModel("Gracias por regalarme un poquito de tu tiempo."),
        QuoteModel("Nada ni nadie podrá hacerme un regalo tan hermoso como el hecho de haber coincidido contigo."),
        QuoteModel("Si fuera un gato, pasaría mis 7 vidas contigo."),
        QuoteModel("No existe en el mundo otra como tú y por eso, me siento orgulloso y afortunado de poder llamarme “tu novio”."),
        QuoteModel("El amor es pura poesía de una persona que no hace versos, sino que da besos."),
        QuoteModel("La medicina de mi alma es tenerte a mi lado."),
        QuoteModel("La vida no es fácil, pero por suerte tú estás en la mía."),
        QuoteModel("No tengo la culpa de que me gustes, la culpa es tuya por tener lo que me encanta."),
        QuoteModel("¿Cómo explicar que muero un poquito cada día por las ganas de verte?"),
        QuoteModel("Me gustan las cosas bonitas. Como tú."),
        QuoteModel("En medio de todo este silencio, tu risa me hace volver a vivir."),
        QuoteModel("Quizás es porque me sentí como en casa contigo mucho antes de que me dejaras entrar en tu corazón."),
        QuoteModel("Me las puedo arreglar solo, pero arreglármelas contigo me parece un mejor plan. "),
        QuoteModel("Te amo tan bonito que me asusta, como asusta la grandeza, la belleza y aquello que, de alguna manera, cambia tu vida para siempre."),
        QuoteModel("Sea lo que sea de lo que estén hechas nuestras almas, la tuya y la mía son las mismas."),
        QuoteModel("Ni en los laboratorios existe tanta química como la que hay entre nosotros."),
        QuoteModel("Tengo ganas de verte y decirte todas las ganas que he tenido de ti."),
        QuoteModel("Cuando te vi, me enamoré y tu sonreíste porque lo sabías."),
        QuoteModel("Nuestro primer beso va a ser legendario."),
        QuoteModel("Para mi corazón basta tu pecho, para tu libertad bastan mis alas."),
        QuoteModel("Hay tinieblas en la vida y hay luces, y tú eres una de las luces, la luz de todas las luces."),
        QuoteModel("Me enamoré como cuando estás quedándote dormido. Primero lentamente, y de repente de golpe."),
        QuoteModel("Nuestro amor es como el viento. No lo puedo ver, pero puedo sentirlo."),
        QuoteModel("Todos tienen un destino y el mío eres tú cuando te encuentre."),
        QuoteModel("Yo existo en dos lugares, aquí y donde tú estés."),
        QuoteModel("Debes permitirme decirte cuánto te admiro."),
        QuoteModel("Te escogí porque me di cuenta de que valía la pena, valía los riesgos, valía la vida."),
        QuoteModel("Entrégame el tiempo que te sobre, y lo gastaré en hacerte la persona más feliz del planeta."),
        QuoteModel("Contigo lo soy todo."),
        QuoteModel("Mi color favorito es verte."),
        QuoteModel("Nos imagino siendo mayores y me entra la risa tonta."),
        QuoteModel("Aceleras mis latidos."),
        QuoteModel("Quiero envejecer contigo."),
        QuoteModel("Revolucionas mis sentidos."),
        QuoteModel("Eres mi pedacito de magia."),
        QuoteModel("Te veo poco, pero te pienso muchísimo."),
        QuoteModel("He cruzado océanos de tiempo para encontrarte."),
        QuoteModel("Perdí la cuenta de todos los besos que quiero darte."),
        QuoteModel("Ningún «escribiendo…» me pone tan feliz como el tuyo."),
        QuoteModel("Me encantaría ser ese chicle para estar todo el día en tu boca."),
        QuoteModel("Si te multan por exceso de belleza ya pagaré tu fianza."),
        QuoteModel("Quería llevarte al cine, pero no permiten entrar con dulces."),
        QuoteModel("Mi nombre es muy largo y difícil de pronunciar, así que mejor llámame mi amor."),
        QuoteModel("Y ahí, entre todos sus gustos raros, estaba yo."),
        QuoteModel("Eres mi notificación favorita."),
        QuoteModel("¿Qué alarma me tengo que poner para despertarme contigo?"),
        QuoteModel("Sabes que no soy de tomar té, pero hoy prefiero tener té."),
        QuoteModel("Así que eres comunista, ¿eh? ¿Qué te parece si compartes tu boca con la mía?"),
        QuoteModel("Si me pagaran por pensar en ti, sería millonario."),
        QuoteModel("Ahorremos agua, duchémonos juntos."),
        QuoteModel("Se me da fatal el inglés: confundí el pasado simple con un futuro contigo."),
        QuoteModel("Perdona si estás cansada. Es mi culpa. Has pasado todo el día paseando por mi mente."),
        QuoteModel("Desde que te conozco, has vivido en mi corazón sin pagar alquiler."),
        QuoteModel("Me tienes que comprar un diccionario, porque desde que te vi me quedé sin palabras."),
        QuoteModel("¿Nos damos un tiempo? Por ejemplo, tú me das tu presente y yo te doy mi futuro."),
        QuoteModel("No me digas que tu madre no es pastelera, porque un bombón como tu no lo hace cualquiera."),
        QuoteModel("Pues sí que ha avanzado la ciencia… ¡Si ya hasta los bombones caminan!"),
        QuoteModel("Mira que me gustas todos los días, pero hoy has exagerado."),
        QuoteModel("No te preocupes: seguirás siendo hermosa con cualquier cosa que te quites."),
        QuoteModel("¿Eres ecologista? ¿Por qué no vienes y me plantas un beso en mi boca?"),
        QuoteModel("Perdón, es que soy ecologista y quiero plantarte unos besos."),
        QuoteModel("Quién fuera bizco para verte dos veces."),
        QuoteModel("Eres tan especial para mí, que recuerdo tu cumpleaños sin el recordatorio."),
        QuoteModel("Debes de ser un virus, porque al verte se me encriptan las palabras."),
        QuoteModel("He cambiado de suavizante, ¿quieres venir a mi casa y olerlo?"),
        QuoteModel("No contestaré a esa pregunta sin la presencia de mi abogado, que temo poder perder el juicio por ti."),
        QuoteModel("¿Te importa que te siga hasta casa? Es que mi madre siempre me decía que persiguiera a mis sueños."),
        QuoteModel("Espero que sepas hacer el boca a boca, porque me acabo de quedar sin aliento."),
        QuoteModel("Tengo hambre de ti. ¿Me acompañas a la mesa?"),
        QuoteModel("Te invito a dormir, o a no dormir… ¡como tú prefieras!"),
        QuoteModel("Si fuera tu pareja sería creyente, porque una diosa como tú no se encuentra en cualquier lado."),
        QuoteModel("No dejo de pensar en otra cosa que no sea tocarte."),
        QuoteModel("Necesito horas extras en el día para recorrerte el cuerpo."),
        QuoteModel("Qué ganas de amar cada centímetro de tu piel."),
        QuoteModel("Me sobran fuerzas para tumbarte en la cama y hacerte el amor."),
        QuoteModel("Eres el camino más placentero que deseo recorrer."),
        QuoteModel("Enciérrame en tus brazos que quiero amanecer en ellos."),
        QuoteModel("No me canso de pensar en cómo hacerte el amor."),
        QuoteModel("Si adivinas en qué estoy pensando, te lo doy en los labios."),
        QuoteModel("Te apuesto un beso a que beso mejor que tú."),
        QuoteModel("Eres muy parecido a mi bebida favorita, porque te me antojas a cada rato."),
        QuoteModel("Te nombro la primera maravilla del mundo."),
        QuoteModel("No te cambiaría por nada del mundo, pero cambiaría el mundo entero solo por ti."),
        QuoteModel("Si con mis letras te seduzco, imagina con mis caricias."),
        QuoteModel("Si ser sexy fuese un delito, te pasarías la vida en la cárcel."),
        QuoteModel("Cuando no te escribo, pasa algo y es que me estoy muriéndome de ganas de escribirte."),
        QuoteModel("Gástame los labios y desnúdame el pensamiento."),
        QuoteModel("Si tú quieres, yo quiero; si te atreves, me atrevo."),
        QuoteModel("Si te hace falta amor, me avisas y lo hacemos."),
        QuoteModel("Te quiero como para leerte cada noche… línea tras línea, espacio por espacio."),
        QuoteModel("Cien corazones no bastarían para poder albergar todo el amor que siento por ti."),
        QuoteModel("Quién fuera un barco para naufragar en lo más profundo de tu corazón…"),
        QuoteModel("Me encantaría verte sin maquillaje cada mañana de mi vida."),
        QuoteModel("¿Has pensado ya dónde vamos a ir en nuestra primera cita?"),
        QuoteModel("Estoy pensando en ti. No importa cuando leas esto."),
        QuoteModel("Si sigo mirándote durante mucho rato necesitaré unos ojos nuevos."),
        QuoteModel("Conmigo de lo que no te faltará será amor, y en caso de que así sea, lo hacemos para resolverlo."),
        QuoteModel("Esa ropa quedaría genial en un montón arrugado en el suelo de mi habitación."),
        QuoteModel("No creo querer bebés, pero no me importaría perfeccionar mi técnica de hacer bebés contigo."),
        QuoteModel("Tienes tan buen aspecto; quiero besar tus labios y subir hasta tu ombligo."),
        QuoteModel("Tus piernas son como una galleta Oreo. Quiero partirlas y comerme todo lo bueno del centro."),
        QuoteModel("Soy ginecólogo autónomo. ¿Cuánto tiempo ha pasado desde tu última revisión?"),
        QuoteModel("Creo que sufres una falta de vitamina yo."),
        QuoteModel("¿Acabas de salir del horno? Porque estás caliente."),
        QuoteModel("Tú debes de ser Medusa, porque me la pones dura como una piedra."),
        QuoteModel("Juguemos al Titanic. Tú serás el barco y yo te lo hundiré."),
        QuoteModel("¿Por qué pagar por un corpiño cuando te sujetaría las tetas todo el día gratis?"),
        QuoteModel("¿Te cabe otra lengua en la boca?"),
        QuoteModel("Tu vestido es muy bonito. ¿Necesitas ayuda para quitártelo sin estropearlo?"),
        QuoteModel("Si estás tan guapa con ropa, debes de estar buenísima sin ella."),
        QuoteModel("Contigo, cada momento se convierte en un recuerdo precioso. Eres la melodía perfecta en mi vida."),
        QuoteModel("En cada latido de mi corazón, resuena tu nombre. Eres mi inspiración, mi razón de ser."),
        QuoteModel("Desde el momento en que te conocí, supe que mi vida había encontrado un propósito más profundo."),
        QuoteModel("En el lienzo de la vida, tú eres el color que ilumina cada rincón de mi existencia."),
        QuoteModel("Tu amor ha transformado mi mundo, llenándolo de color y significado."),
        QuoteModel("A tu lado, cada día es una aventura emocionante y cada desafío se convierte en una oportunidad para crecer juntos."),
        QuoteModel("Cada día a tu lado es un lienzo en blanco esperando ser pintado con los pinceles del amor, la complicidad y la pasión."),
        QuoteModel("Juntos hemos creado un cuadro único, lleno de momentos inolvidables y experiencias que atesoro en lo más profundo de mi corazón."),
        QuoteModel("Gracias por ser mi musa, mi inspiración y mi razón de ser."),
        QuoteModel("En el tejido de nuestras vidas, cada hilo de tu presencia se entrelaza con el mío, creando un patrón de amor y complicidad que es único."),
        QuoteModel("Gracias por ser la persona que ilumina mis días con su sonrisa y que llena mi corazón con su amor incondicional."),
        QuoteModel("Contigo, cada capítulo de nuestra historia se vuelve más emocionante y lleno de significado."),
        QuoteModel("Cuando miro atrás en el camino que hemos recorrido juntos, veo un viaje lleno de altibajos, risas y lágrimas, pero sobre todo, veo el amor que nos ha mantenido unidos en cada momento."),
        QuoteModel("Tú eres mi luz en la oscuridad y mi motivo para seguir adelante."),
        QuoteModel("A tu lado, he aprendido a ser más fuerte, más valiente y más amable."),
        QuoteModel("Gracias por llenar mi mundo con tu amor incondicional y tu presencia siempre reconfortante."),
        QuoteModel("Desde el primer momento que cruzamos miradas, supe que tú serías mi más grande aventura. "),
        QuoteModel("En este viaje llamado vida, tú has sido mi destino más hermoso."),
        QuoteModel("Cada momento a tu lado es un regalo que atesoro con cariño en lo más profundo de mi corazón."),
        QuoteModel("Tu amor es el faro que me guía en medio de la oscuridad, la brújula que me orienta cuando me siento perdido y el abrazo que me reconforta en los momentos difíciles."),
        QuoteModel("Gracias por ser mi refugio seguro, mi mejor amiga y mi amor eterno."),
        QuoteModel("Cuando te veo me siento como en la playa: tus ojos son como el sol y tu sonrisa es como una ola."),
        QuoteModel("Mi corazón y las flores tienen algo en común: florecen cuando escuchan tu voz."),
        QuoteModel("Dos palabras, un sentimiento: Te amo."),
        QuoteModel("Tantas sonrisas en el mundo y la tuya es mi favorita."),
        QuoteModel("Te quiero cuando sonríes, te quiero cuando suspiras, te quiero cuando estás lejos y te quiero todos los días."),
        QuoteModel("Eres mi lugar favorito, ese del que no me quiero ir jamás."),
        QuoteModel("No importa en dónde estés: yo seré quien te ame por siempre."),
        QuoteModel("No importa que nos enojemos y que tengamos malos ratos: yo siempre voy a ser feliz de haberte conocido."),
        QuoteModel("Todas las noches anhelo estar a tu lado."),
        QuoteModel("Puedes estar lejos de mis ojos, pero no de mi corazón."),
        QuoteModel("Pensar en ti es mi forma de abrazarte, acariciarte y decirte cuánto te amo. "),
        QuoteModel("Tus brazos son mi puerto y tus ojos mi mar en calma."),
        QuoteModel("Mi corazón se acelera con solo oír tu voz."),
        QuoteModel("Cuando te veo, mi corazón hace big bang."),
        QuoteModel("Te quiero hasta los límites del universo."),
        QuoteModel("Me encanta despertarme con un mensaje tuyo."),
        QuoteModel("Me encanta que me mires y sonrías sin ninguna explicación."),
        QuoteModel("Eres la mejor sensación del mundo."),
        QuoteModel("La perfección no existe, pero para mí eres perfecta."),
        QuoteModel("Me gusta tu perfume, hueles al amor de mi vida."),
        QuoteModel("El destino de nuestros labios es encontrarse."),
        QuoteModel("Eres perfecta para mí."),
        QuoteModel("Mi corazón te pertenece."),
        QuoteModel("Mi alma te pertenece."),
        QuoteModel("Mi cuerpo te pertenece."),
        QuoteModel("Te quiero hasta el infinito y más allá."),
        QuoteModel("Me enamoro más de mil veces al día, y todas son de ti."),
        QuoteModel("Ojalá pierdas la calma y vengas a enloquecer conmigo."),
        QuoteModel("Los finales felices no existen, porque las buenas historias nunca terminan."),
        QuoteModel("Somos una casualidad llena de intención."),
        QuoteModel("Si volviera a nacer, te volvería a elegir."),
        QuoteModel("La vida está llena de cosas bonitas, por ejemplo, tú."),
        QuoteModel("Te amo, no solo por lo que tú eres, sino también por lo que yo soy cuando estoy contigo."),
        QuoteModel("Te quiero. Te quiero por tu bravura y tu tenacidad, y tu brío y tu implacable dureza."),
        QuoteModel("Quiero llenar mi boca con tu nombre."),
        QuoteModel("No necesito el cielo si tú no puedes ir a él."),
        QuoteModel("Ven a dormir conmigo. No haremos el amor, el amor nos hará."),
        QuoteModel("Amar no es mirarse el uno al otro; es mirar juntos en la misma dirección."),
        QuoteModel("Si tú me recuerdas, no me importará que el resto del mundo me olvide."),
        QuoteModel("De nadie seré, solo de ti. Hasta que mis huesos se vuelvan cenizas y mi corazón deje de latir."),
        QuoteModel("Prefiero morir mañana que vivir cien años sin conocerte."),
        QuoteModel("Ya me tenías con el 'Hola'."),
        QuoteModel("Tápate los oídos, fuerte, fuerte, fuerte, más fuerte todavía... ¿oyes lo mucho que te quiero?"),
        QuoteModel("Quiero oírte pronunciar mi nombre."),
        QuoteModel("Debo decirle que ha embrujado usted mi cuerpo y mi alma."),
        QuoteModel("Odio no poder odiarte."),
        QuoteModel("El amor es una palabra muy débil para describir lo que siento por ti."),
        QuoteModel("Cuando dices que me amas, ten presente que yo te amo más."),
        QuoteModel("Estaré allí cuando llores y cuando rías, en tus días de melancolía y en tus alegrías."),
        QuoteModel("No quiero conocer otro beso, no quiero otro nombre saliendo de mis labios."),
        QuoteModel("Hay gente que lo quiere todo, pero todo no significa nada si no te tengo a ti."),
        QuoteModel("Antes que ver el sol, prefiero escuchar tu voz."),
        QuoteModel("Si quieres las estrellas, vuelco el cielo."),
        QuoteModel("El amor solo es una palabra, pero tú le aportas definición."),
        QuoteModel("Si todo el mundo estuviera mirándonos, seguiría bailando contigo."),
        QuoteModel("Toma un pedazo de mi corazón y hazlo tuyo, así cuando estemos separados nunca te sentirás sola."),
        QuoteModel("En tus ojos veo algo más bonito que las estrellas."),
        QuoteModel("Te quiero igual que un hombre que se ahoga y quiere aire."),
        QuoteModel("Estoy catastróficamente enamorado de ti."),
        QuoteModel("Me enamoro de la forma en que me tocaste sin usar las manos."),
        QuoteModel("Vamos, cariño, enciende mi fuego."),
        QuoteModel("En un beso sabrás todo lo que he callado."),
        QuoteModel("No eres mi número uno, eres el único."),
        QuoteModel("Tu voz es mi sonido favorito."),
        QuoteModel("Puede que no sea tu primera cita, beso y amor… pero quiero ser tu último todo."),
        QuoteModel("Robaste mi corazón pero te dejaré tenerlo."),
        QuoteModel("Cruzaría océanos solo por verte sonreír."),
        QuoteModel("Si vas a estar en mi cabeza dando vueltas todo el día, al menos vístete."),
        QuoteModel("Es mejor un ‘te quiero’ a diario que no un regalo cuando lo diga el calendario."),
        QuoteModel("No puedo darte lo mejor del mundo, pero te voy a dar... te voy a dar."),
        QuoteModel("Cariño... todo en exceso es malo... menos yo."),
        QuoteModel("Oye, te quiero como quieren los patos. ¿Cómo? Patodalavida."),
        QuoteModel("El físico no importa, pero tus nalgas me enamoran."),
        QuoteModel("Si supieras cuánto te pienso, me denunciarías por acoso mental."),
        QuoteModel("Eres la pizza de mi corazón, siempre quiero más."),
        QuoteModel("Soy para tu corazón lo que es una milanesa para tu estómago."),
        QuoteModel("Si fueras un parque de atracciones, serías el más emocionante."),
        QuoteModel("¿Tu regalo? Soy yo. De nada."),
        QuoteModel("Me gustas lo suficiente como para querer mantenerte."),
        QuoteModel("Eres como la chancla de mi mamá: te veo venir y se me acelera el corazón."),
        QuoteModel("No soy un perro, pero guau contigo."),
        QuoteModel("El megalodón se extinguió, pero veo que tu madre logró dar vida al megabombón."),
        QuoteModel("Are you a sofa? Because you are sofackingg precious."),
        QuoteModel("Are you an aguacate? Because te comía avocados."),
        QuoteModel("La lengua es el músculo más fuerte del cuerpo, ¿luchamos?"),
        QuoteModel("Estudiando Derecho para ir derechito a tu cuarto."),
        QuoteModel("Mi madre opina que deberías casarnos."),
        QuoteModel("Hola, me da miedo tu ropa, ¿te la puedes quitar, porfa?"),
        QuoteModel("Quién fuera cemento para sujetar semejante monumento."),
        QuoteModel("Te iba a decir que eres hermosa, pero la verdadera belleza está en el interior y aún no he estado dentro de ti."),
        QuoteModel("Mátame si no te sirvo. Pero primero pruébame."),
        QuoteModel("Las rosas son rojas, el viento las mueve, yo soy un 6 y tú eres un 9."),
        QuoteModel("Quiero ser Photoshop para retocarte todo el cuerpo."),
        QuoteModel("Te quiero. Luego te digo en qué posición."),
        QuoteModel("Si tuviera que regalarte algo te regalaría una espejo, porque después de ti los más bonito es tu reflejo."),


    )
}